#!/bin/bash
#FILE= $(<$1)
#echo "$FILE"

function gitCommit {
    git add -A .
    git commit -m "automated commit from script"
    git push -u origin master
}

if [ "$#" -eq 0 ]
then
    echo "Pass in a File name"
    exit 1
fi

# count number of lines
printf "Number of lines in the file is "
wc -l $1

# count number of words
printf "\nNumber of words in the file is "
wc -w $1

# find most repetitive word
printf "\nMost repetitive word is "
tr -c '[:alnum:]' '[\n*]' < $1 | sort | uniq -c | sort -nr | head  -1

# find least repetitive word
printf "\nLeast repetitive word is "
tr -c '[:alnum:]' '[\n*]' < $1 | sort | uniq -c | sort | head  -1

# find words based on regex patterns
# starts with "d" and ends with "d" can be upper or lower
#sed '/d.*d//Ig'
printf "Number of words that start and end with d or D is \n"
grep -Ewo '[dD].*[dD]' $1 | wc -w

# starts with "A" or "a" and ends with anything
printf "\nNumber of words that start with A or a\n"
grep -Ewo '[aA].*[^ ]' $1 | wc -w

# count numeric words
printf "\nNumber of numeric words are\n"
grep -Ewo '[0-9][0-9]*' $1 | wc -w

# count alphanumeric words
printf "\nNumber of alphanumeric words\n"
#grep -Ewo "[a-zA-Z0-9]*" $1 | wc -w
grep -Eow '[a-zA-Z0-9]*' $1 | sed 's/^[0-9]*//g' | sed 's/^[a-zA-Z]*//g' | wc -w

